name = input('Enter Your Name:\n')
age = input("Enter Your Age:\n")
money = input("How much money do you have: \n")
happy = input("Are You Happy: \n")

print("##############")
print("Name: " + name)
print("Age: " + age)
print("Money: " + money)
print("Happines: " + happy)
print("##############")